spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bharathmit/cloud-config
          default-label: master
          clone-on-start: true
server:
  port: 8099
