spring:
  application:
    name: review
  config:
    import: optional:configserver:http://localhost:8099

  sleuth:
    sampler.probability: 1
      
server:
  port: 8030

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    healthcheck:
      enabled: true

info:
  app:
    name: Spring Boot Review Application
    description: ${info.app.name} is Running on ${server.port} port

management:
  endpoints:
    web:
      exposure:
        include: "*"

    
    
  
      
  
