FROM openjdk:8
MAINTAINER Bharath Mannaperumal <bharathkumar.feb14@gmail.com>
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} registry.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/registry.jar"]