spring:
  application:
    name: product
  config:
    import: optional:configserver:http://localhost:8099

  sleuth:
    sampler.probability: 1
      
server:
  port: 8010
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

    
    
  
      
  
