spring:
  application:
    name: inventory
  config:
    import: optional:configserver:http://192.168.0.109:8099

  sleuth:
    sampler.probability: 1
      
server:
  port: 8020
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

    
    
  
      
  
