spring:
  application:
    name: inventory
  config:
    import: optional:configserver:http://localhost:8099
  profiles:
    active: local
  sleuth:
    sampler.probability: 1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/spring-msa
server:
  port: 8020

client:
  registration: gateway-service, product-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    healthcheck:
      enabled: true

info:
  app:
    name: Spring Boot Inventory Application
    description: ${info.app.name} is Running on ${server.port} port

logging:
  level:
    org:
      springframework:
        web: debug


management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"

    
    
  
      
  
