spring:
  application:
    name: api-gateway-service
  config:
    import: optional:configserver:http://localhost:8099

  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/** , /product-service/v3/api-docs
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventorys/** , /inventory-service/v3/api-docs
          filters:
            - RewritePath=/inventorys/(?<segment>.*), /$\{segment}
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/** , /review-service/v3/api-docs
          filters:
            - RewritePath=/reviews/(?<segment>.*), /$\{segment}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    healthcheck:
      enabled: true


server:
  port: 8040

management:
  info:
    env.enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /product-service/v3/api-docs
        name: Product Service
        primaryName: Products Service
      - url: /inventory-service/v3/api-docs
        name: Inventory Service
        primaryName: Inventory Service
      - url: /review-service/v3/api-docs
        name: Review Service
        primaryName: Reviews Service

info:
  app:
    name: Spring Boot Gate way Application
    description: ${info.app.name} is Running on ${server.port} port