spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://192.168.0.109:8099

  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*), /$\{segment}
        - id: inventory-service
          uri: lb://INVENTORY
          predicates:
            - Path=/inventorys/**
          filters:
            - RewritePath=/inventorys/(?<segment>.*), /$\{segment}
        - id: review-service
          uri: lb://REVIEW
          predicates:
            - Path=/reviews/**
          filters:
            - RewritePath=/reviews/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

server:
  port: 8040

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Spring Boot Gate way Application
    description: ${info.app.name} is Running on ${server.port} port