spring:
  application:
    name: registry 

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0