version: "3.5"
services:

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.27.1
    ports:
      - "9090:9090"
    networks:
      - spring-microservice-network
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.7
    ports:
      - "3000:3000"
    networks:
      - spring-microservice-network

#docker network create -d bridge spring-microservice-network
networks:
  spring-microservice-network:
    external: true